src/components/header/index.tsx, src/components/header/styles.ts, src/components/locale-switcher/index.tsx, src/components/locale-switcher/styles.ts
Create the locale switcher component
=> feat(locale-switcher): create locale switcher

public/navigation.json, src/pages/docs/guides/[slug].tsx, src/pages/updates/announcements/index.tsx, src/utils/getDocsPaths.ts, src/utils/getReleasePaths.ts
=> fix(slug): test en locale

src/components/sidebar-elements/index.tsx
Remove api-reference case from sidebar-elements
=> fix(sidebar-elements): remove api case

src/utils/getDocsPaths.ts, src/utils/getReleasePaths.ts
=> fix(getdocspaths): fix paths

package.json, src/utils/remark_plugins/remarkReadingTime.ts, yarn.lock
To update the Components library version.
=> chore(package.json): update components lib version

src/components/tag/styles.ts
Change product tags color
Enhance accessibility
=> feat: changed product tags colors

package.json, src/pages/_app.tsx, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tutorial/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/known-issues/[slug].tsx, src/styles/code-hike-theme.ts
Change code blocks so they have a better background and a working copy button
Legibility of texts inside code blocks and enhancing its usability by enabling to copy the text through a copy button
=> feat: working code block

src/components/filter/styles.ts
Change the filter button height
=> fix: filter button height

src/styles/code-hike-theme.ts
Make the code blocks theme match the one in the developers portal
The themes not matching
=> fix: theme to match devportal

public/navigation.json
update navigation.json file with new announcements sorting (from most recent to oldest) as generated by https://github.com/vtexdocs/help-center-content/pull/46
https://github.com/vtexdocs/helpcenter/issues/43
=> fix(navigation): update announcements sorting

src/components/header/index.tsx, src/messages/en.json, src/messages/es.json, src/messages/pt.json
Removing the satisfaction research announcement bar.
Accessing the portal home.
=> chore: remove satisfaction research announcement bar

src/styles/documentation-page.ts
add list spacing (same as [devportal](https://github.com/vtexdocs/devportal/blob/main/src/styles/documentation-page.ts#L28))
[spacing between list items is too small](https://www.notion.so/Spacing-between-list-items-is-too-small-a021d9d72dcf4f1ba8caada3c7888f39?pvs=21)
visit `en/docs/tutorial/how-to-manually-invoice-an-order` or any other guide with a list
=> style: add list spacing

package.json
using the components version defined here https://github.com/vtexdocs/components/pull/42
=> fix(package.json): filter search results by language

src/pages/api/ki-createupdate.ts, src/pages/api/ki-gettree.ts
=> feat(apis): add github calls to api

src/pages/troubleshooting/index.tsx
[EDU-15391](https://vtex-dev.atlassian.net/browse/EDU-15391)
https://github.com/vtexdocs/helpcenter/issues/229
=> fix: modify troubleshooting items per page to 8

src/pages/api/ki-createupdate.ts
=> fix: fix create/update api

src/pages/api/ki-delete.ts
Adding an API to delete a known issue (useful for scenarios when a KI title changes and consequently we need to erase the existing file with the old slug and create another with the new slug).
=> feat(ki): delete known issue api

src/components/layout.tsx
To identify users returning to the old version
=> feat(announcement bar href): add utm source

src/components/layout.tsx, src/components/newsletter-section/index.tsx, src/components/page-header/index.tsx, src/pages/404.tsx, src/pages/500.tsx, src/pages/announcements/index.tsx, src/pages/docs/tracks/index.tsx, src/pages/docs/tutorials/index.tsx, src/pages/faq/index.tsx, src/pages/index.tsx, src/pages/known-issues/index.tsx, src/pages/troubleshooting/index.tsx, src/utils/contexts/trackerContext.tsx
This PR addresses critical performance issues identified in the Lighthouse audit of https://newhelp.vtex.com/.
**LCP (Largest Contentful Paint) Improvements:**
- ✅ Added `priority` prop to hero image (`landing.png`) in NewsletterSection to prevent lazy loading
- ✅ Added preload hints for critical LCP image
- ✅ Expected improvement: ~10+ seconds reduction in LCP time
**JavaScript Execution Optimizations:**
- ✅ Changed Google Tag Manager script strategy from `afterInteractive` to `lazyOnload`
- ✅ Added 100ms delay for OpenReplay tracker initialization to prevent main thread blocking
- ✅ Improved tracker provider state management to prevent duplicate initialization
**Resource Loading Optimizations:**
- ✅ Added DNS prefetch hints for third-party domains (GTM, Google Analytics, OpenReplay)
- ✅ …
=> feat: implement performance optimizations based on Lighthouse audit

algolia/scraper_md.json, navigation-optimization-strategy.md, next.config.js, src/pages/server-sitemap.xml/index.ts, src/utils/getNavigation.ts
changing the netlify deploy URL (leafy-mooncake) for the traffic test URL (newhelp.vtex.com)
=> chore(url occurrences): change URL (newhelp.vtex.com)

src/pages/known-issues/[slug].tsx, src/pages/known-issues/index.tsx, src/utils/getDocsPaths.ts
=> feat: known issues integration

package.json, src/components/pagination/index.tsx, src/pages/announcements/index.tsx, src/pages/faq/index.tsx, src/pages/index.tsx, src/pages/known-issues/index.tsx, src/pages/troubleshooting/index.tsx, src/utils/fetchBatchGithubData.ts, src/utils/getDocsPaths.ts, src/utils/logging/log-util.ts
=> refactor(pages): separate reusable fetchBatch code

package.json, public/navigation.json, src/components/layout.tsx, src/components/tutorial-markdown-render/index.tsx, src/pages/announcements/[slug].tsx, src/pages/announcements/index.tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tracks/index.tsx, src/pages/docs/tutorials/index.tsx, src/pages/faq/[slug].tsx, src/pages/faq/index.tsx, src/pages/known-issues/[slug].tsx, src/pages/search/index.tsx, src/utils/constants.ts, src/utils/typings/unionTypes.ts
Fixes the Search Results classification
=> fix(search): update components package to v6.0.6

src/components/icons/graph-icon.tsx, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tutorials/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/known-issues/[slug].tsx, src/pages/troubleshooting/[slug].tsx, src/utils/extractStaticPropsParams.ts, src/utils/fetchFileContributors.ts, src/utils/fetchRawMarkdown.ts
=> refactor(pages): refactor pages for easier maintanability

src/pages/announcements/[slug].tsx, src/pages/docs/tutorials/[slug].tsx
=> fix(tutorials): fix keyPath usage

package.json, src/components/announcement-card/index.tsx, src/components/announcement-card/styles.ts, src/pages/announcements/index.tsx, src/pages/troubleshooting/[slug].tsx, src/utils/typings/types.ts
=> feat(pages): add synopsis to announcements cards

src/components/tutorial-markdown-render/index.tsx, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tutorials/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/known-issues/[slug].tsx, src/pages/troubleshooting/[slug].tsx
=> fix(pages): redirect to localized if keypath

package.json
=> fix(package.json): fix search results page

src/components/locale-switcher/index.tsx, src/pages/troubleshooting/[slug].tsx
=> fix(locale-switcher): enable locale switcher for troubleshooting docs

public/navigation.json
=> chore(navigation.json): update navigation

src/components/author/index.tsx, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tutorials/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/known-issues/[slug].tsx, src/pages/troubleshooting/[slug].tsx, src/utils/constants.ts, src/utils/fetchFileContributors.ts, src/utils/fetchGithubUser.ts
=> feat(announcmenets): display contentful author

public/navigation.json, src/components/faq-section-card/styles.ts, src/components/faq-section/styles.ts, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/docs/tutorials/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/index.tsx, src/pages/known-issues/[slug].tsx, src/pages/troubleshooting/[slug].tsx, src/utils/getPagination.ts
=> fix(pages): various improvements

src/pages/known-issues/index.tsx
=> fix: replace contentful id with zendesk id in ki list

src/pages/_app.tsx
=> chore(_app.ts): update meta-image

src/pages/known-issues/[slug].tsx
[EDU-14485](https://vtex-dev.atlassian.net/browse/EDU-14485)
=> feat: add ki product team to ki page

public/navigation.json, src/components/tutorial-index/index.tsx, src/pages/announcements/index.tsx, src/pages/docs/tutorials/[slug].tsx, src/pages/faq/index.tsx, src/pages/known-issues/index.tsx, src/styles/documentation-page.ts
=> fix(faq): fix faq filters not being applied

src/components/TimeToRead/index.tsx, src/components/TimeToRead/styles.ts, src/components/article-pagination/index.tsx, src/components/article-render/index.tsx, src/components/author/index.tsx, src/components/author/styles.ts, src/components/breadcrumb/styles.ts, src/components/date-text/styles.ts, src/pages/announcements/[slug].tsx, src/pages/docs/tracks/[slug].tsx, src/pages/faq/[slug].tsx, src/pages/known-issues/[slug].tsx, src/pages/troubleshooting/[slug].tsx, src/utils/article-page/getBreadcrumbsList.ts
=> refactor(pages): refactor content types to show category index

src/pages/troubleshooting/[slug].tsx
=> fix(troubleshooting): fix article index path

src/components/article-index/index.tsx, src/styles/announcement-page.ts, src/styles/documentation-page.ts
=> feat(article-index): add copy button and improve styles
