vtexdocs/helpcenter

- src/components/last-updates-card/index.tsx
- src/components/locale-switcher/index.tsx
- src/components/release-note/functions.tsx
- src/components/release-note/index.tsx
- src/pages/docs/guides/[slug].tsx
- src/pages/index.tsx
- src/pages/updates/announcements/[slug].tsx
- src/utils/getDocsPaths.ts
- src/utils/getReleasePaths.ts
The `help-center-content` repository as organized as in the following:
- `docs`
- `en`
- `pt`
- `es`
- `announcements`
- `en`
- `pt`
- `es`
Considering this change, the `getDocsPaths` and `getReleasePaths`were updated to consider the locale folder.
> feat(getdocspaths): get docs paths considering locale folder

- public/navigation.json
- src/components/sidebar-elements/index.tsx
- src/components/sidebar/index.tsx
- src/pages/docs/guides/[slug].tsx
- src/pages/updates/announcements/[slug].tsx
- src/utils/navigation-utils.ts
Enable sidebar localization. 
The `name` field of the `navigation.json` file now has the following structure:
```
"name": {
"en": "Getting Started",
"pt": "Primeiros Passos",
"es": "Primeros pasos"
},
```
The `name` value corresponding to the current locale is used.
> feat(navigation-utils): enable navigation localization

- src/utils/constants.ts
Update placeholders from menu to right links.
Update placeholders from menu to right links.
Just fix hyperlinks.
Go to the menu and verify if each item routes to the right page. Specially health check, and status . But feel free to check others as well.
1. Go to menu and choose an item.
2. Check if it rout to the right page.
> fix: changes links in constants file

- src/components/known-issue-card/index.tsx
Add translation of status tags in the known issues cards.
Open the preview and check the translations.
> feat(known-issues): add status translation

- src/pages/docs/tracks/[slug].tsx
Since we decided not to use reference numbers in track articles page titles, this part of the code was generating a bug, described in issue 86. So this PR removes it.
I tested this locally, and it worked fine.
1. Run the portal locally.
2. Access this [article](http://localhost:3000/pt/docs/tracks/integration-overview).
3. See if the first word in the page header is doubled.
> Fix doubled first words in track articles' titles

- src/utils/getDocsPaths.ts
- tsconfig.json
…to match new folder structure
This `help-center-content` [PR](https://github.com/vtexdocs/help-center-content/pull/29) changes the repository's folder structure to match the portal's content architecture. This means we need to change the way we get/validate docs paths from github.
1. Run the portal locally from this branch, using `/api/preview?branch=edit-folder-structure`.
2. Try to access different articles.
> Fix docs paths validation 

- src/pages/faq/index.tsx
- src/pages/known-issues/index.tsx
It was not possible to preview content in the FAQ and KI pages before because the fetching of the docs paths occurred outside of getStaticProps. This PR fixes it.
Learn more on this problem and how to test in [issue 101](https://github.com/vtexdocs/helpcenter/issues/101).
> Fix content preview branch selection on KI and FAQ pages

- src/components/TimeToRead/index.tsx
- src/components/TimeToRead/styles.ts
- src/components/tutorial-markdown-render/index.tsx
- src/pages/docs/tracks/[slug].tsx
- src/pages/faq/[slug].tsx
- src/pages/known-issues/[slug].tsx
- src/styles/documentation-page.ts
Change the way the time to read docs pages work, only displaying when the estimated time is higher or equal to 5 minutes
> feat: display time to read article only if higher than 5 minutes

- src/styles/documentation-page.ts
- src/styles/global.css
Make tables columns have a minimum width
Tables columns headers being too small depending on device
> fix: word breaking and width off tables columns

- src/components/breadcrumb/index.tsx
Fixing breadcrumbs from some articles having a link to a unexisting page
Breadcrumbs having links to pages that do not exist yet
> fix: breadcrumbs rendering link instead of text

- src/components/known-issue-card/index.tsx
- src/components/tag/styles.ts
- src/pages/known-issues/index.tsx
- src/utils/constants.ts
- src/utils/typings/types.ts
Fix the Known Issues card tag "No Fix" to properly display and fix no cards matching this tag
Known Issues cards with the tag "No fix" displaying the intl id
> fix: no fix status for ki cards

- src/components/known-issue-card/index.tsx
- src/pages/announcements/[slug].tsx
- src/pages/announcements/index.tsx
- src/pages/docs/tracks/[slug].tsx
- src/pages/docs/tutorial/[slug].tsx
- src/pages/faq/[slug].tsx
- src/pages/faq/index.tsx
- src/pages/index.tsx
- src/pages/known-issues/[slug].tsx
- src/pages/known-issues/index.tsx
- src/pages/troubleshooting/[slug].tsx
- src/pages/troubleshooting/index.tsx
- src/utils/typings/types.ts
hiding unpublished content (where the frontmatter status is different from `PUBLISHED`), making their pages return 404 and removing them from lists of known issues, faq, announcements, and troubleshooting.
https://github.com/vtexdocs/helpcenter/issues/105
> feat: hide unpublished content

- package.json
- src/utils/string-utils.ts
This PR updates the slugify function (ToC) to correctly handle accented characters in Portuguese and Spanish. It now:
- Removes diacritics using normalize('NFD') (e.g., "condições" → "condicoes").
- Preserves word structure while keeping only alphanumeric characters, spaces, and hyphens.
- Fixes incorrect slug generation for accented words.
ID generation is addressed separately in [PR #39](https://github.com/vtexdocs/components/pull/39)
> fix(package.json): fix incorrect slug generation for words with accents

- src/pages/api/disable-preview.ts
- src/pages/api/preview.ts
Restore preview api routes to restore content branch preview function
Testing:
1. Sync with this branch.
2. Run `yarn dev`.
3. Go to the preview url for branch `test-preview-2`:
```
http://localhost:3000/api/preview?branch=test-preview-2
```
4. Visit this article:
```
http://localhost:3000/pt/docs/tutorial/assembly-options
```
5. The first paragraph should be just the word `teste`.
> fix(preview pages)

- src/pages/announcements/[slug].tsx
- src/pages/docs/tracks/[slug].tsx
- src/pages/docs/tutorials/[slug].tsx
- src/pages/faq/[slug].tsx
- src/pages/troubleshooting/[slug].tsx
- src/utils/redirectToLocalizedUrl.ts
This change fixes issue #202.
To test it you can try and access links with mismatched locale and slug. Examples:
- Tutorial: https://deploy-preview-209--leafy-mooncake-7c2e5e.netlify.app/es/docs/tutorials/how-my-account-works
- Track: https://deploy-preview-209--leafy-mooncake-7c2e5e.netlify.app/pt/docs/tracks/configuracion-inicial
- FAQ: https://deploy-preview-209--leafy-mooncake-7c2e5e.netlify.app/pt/faq/how-to-find-linkedin-pixel
- Troubleshooting: https://deploy-preview-209--leafy-mooncake-7c2e5e.netlify.app/en/troubleshooting/como-corregir-el-error-de-esquema-en-aplicaciones-b2b
- Annoucnement: https://deploy-preview-209--leafy-mooncake-7c2e5e.netlify.app/en/announcements/2024-09-18-alteracao-no-campo-availablequantity-da-api-de-busca
The expected behavior is that the browser is …
> Mismatched locale slug handling

- src/components/tutorial-markdown-render/index.tsx
This PR solves #207 .
The CopyLinkButton component was previously placed within the TutorialMarkdownRender component's header text. I changed it to be 'parallel' to the header text and tweeked the flex params so that it is displayed correctly.
You can compare any given tutorial, such as [this one](https://leafy-mooncake-7c2e5e.netlify.app/pt/docs/tutorials/como-funciona-a-minha-conta) with the same version in the deploy preview. Upon inspecting the header element in dev mode, you should be able to spot the difference, like in the screenshots below.
> fix(tutorial-markdown-renderer): remove copy link button from h1

- src/components/layout.tsx
- src/messages/en.json
- src/messages/es.json
- src/messages/pt.json
Add announcement bar allowing users to return to previous version during the traffic tests with the new portal.
[Deploy preview](https://deploy-preview-231--leafy-mooncake-7c2e5e.netlify.app/pt)
> Traffic tests announcement bar

- .github/workflows/release-version.yml
Improves the release workflow to handle tag conflicts and provide better error handling during the release process.
- **Pre-validation**: Added a step to check if the calculated tag already exists before attempting to create it
- **Error handling**: Enhanced the push step to handle failed pushes with proper cleanup
- **Logging**: Added detailed logging to show what version will be created
- **Conditional execution**: Tag checking only runs when a release is actually being performed
Previously, if a tag already existed (manually created or from a failed workflow), the release workflow would fail at the push step without clear error messages or cleanup. This could leave the repository in an inconsistent state.
- Uses  to determine the next version before creating it
- Handles different …
> ci: improve release workflow with tag conflict handling

- src/components/article-pagination/index.tsx
- src/messages/en.json
- src/messages/es.json
- src/messages/pt.json
Localization of the article pagination component.
[EDU-15740](https://vtex-dev.atlassian.net/browse/EDU-15740)
Article pagination was always in English regardless of the selected locale.
> feat: localize article pagination

- src/components/header/index.tsx
- src/components/layout.tsx
This PR fixes the behavior of the scrolling header. Previously, the header would disappear when the user scrolled down the page, disrupting navigation and accessibility. With this fix, the header now remains visible (sticky) as the user scrolls, improving usability and ensuring consistent access to key actions or navigation elements.
|**Before:**|**Now:**|
|--|---|
|<img width="1470" height="796" alt="Screenshot 2025-08-04 at 11 20 59" src="https://github.com/user-attachments/assets/2a75515e-dbe9-4e52-9dc4-84e43c213640" />|<img width="1470" height="796" alt="Screenshot 2025-08-04 at 11 23 32" src="https://github.com/user-attachments/assets/3aea4bfb-3fb8-47a6-9801-5f1e3246a1e6" />
> fix(header): fix announcement bar and header behavior

- src/pages/known-issues/[slug].tsx
- src/utils/resolveSlugFromKiFormat.ts
Adding an alternative route for known issues, namely `{locale}/known-issues/ki--{zendeskId}`.
[EDU-14999](https://vtex-dev.atlassian.net/browse/EDU-14999)
Go to a KI page using `{locale}/known-issues/ki--{zendeskId}`. Example: `/en/known-issues/ki--1157944`. You will get the KI mapped in [this file](https://raw.githubusercontent.com/vtexdocs/known-issues/refs/heads/main/.github/ki-slugs-and-zendesk-ids.json) for that ID.
> feat: add ki alternative route
